"""empty message

Revision ID: a764a11544f6
Revises: 69a2f2c071e7
Create Date: 2018-03-25 22:28:18.826078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a764a11544f6'
down_revision = '69a2f2c071e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alarm', sa.Column('friday', sa.Boolean(), nullable=True))
    op.add_column('alarm', sa.Column('saturday', sa.Boolean(), nullable=True))
    op.add_column('alarm', sa.Column('sunday', sa.Boolean(), nullable=True))
    op.add_column('alarm', sa.Column('thursday', sa.Boolean(), nullable=True))
    op.add_column('alarm', sa.Column('tuesday', sa.Boolean(), nullable=True))
    op.add_column('alarm', sa.Column('wednesday', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alarm', 'wednesday')
    op.drop_column('alarm', 'tuesday')
    op.drop_column('alarm', 'thursday')
    op.drop_column('alarm', 'sunday')
    op.drop_column('alarm', 'saturday')
    op.drop_column('alarm', 'friday')
    # ### end Alembic commands ###
