"""empty message

Revision ID: a9dd8fb3d96f
Revises: 883dc4c5de8a
Create Date: 2018-05-02 15:56:04.240054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9dd8fb3d96f'
down_revision = '883dc4c5de8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alarm', sa.Column('time', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_alarm_time'), 'alarm', ['time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alarm_time'), table_name='alarm')
    op.drop_column('alarm', 'time')
    # ### end Alembic commands ###
